### ISSUE TITLE
group_concat ordered values fail for tests

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#154]
### A clear and concise description of what the bug is.

I seems as if SQLAlchemy has an aggregate ORDER BY for [PostgreSQL](https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#sqlalchemy.dialects.postgresql.aggregate_order_by) only. Something as

```
func.group_concat(T1.col.distinct(), order_by=T1.col.asc())
```

does not work in 2.0.

For MySQL, we can do the following

```
func.group_concat(T1.col.distinct().op("ORDER BY")(T1.col))
```

This cannot be replaced by `order_by`, as it returns a new selectable, inherited from a `GenerativeSelect`. This results in `AttributeError: 'Comparator' object has no attribute 'order_by'`.

But for testing, this unfortunately does not work. This is not an SQLAlchemy issue, but a sqlite3 DBAPI module-related issue. Query parameters can only be used to pass column values, not column names or other SQL keywords, see *e.g.*

```python
import sqlite3

cnxn = sqlite3.connect(":memory:")
crsr = cnxn.cursor()
crsr.execute("CREATE TABLE table1 (id int primary key, txt varchar(10))")
cnxn.commit()
crsr.executemany("INSERT INTO table1 (id, txt) VALUES (?, ?)", [(21, "Alfa"), (6, "Omega")])
cnxn.commit()

col_name = "txt"
direction = "ASC"

sql = "SELECT * FROM table1 ORDER BY ? ?"
crsr.execute(sql, (col_name, direction))
# sqlite3.OperationalError: near "?": syntax error

sql = f"SELECT * FROM table1 ORDER BY {col_name} {direction}"
crsr.execute(sql)
print(crsr.fetchall())
# [(21, 'Alfa'), (6, 'Omega')]
```

I am unsure how to tackle this. I don't want to drop the tests alltogether for this service. One possible way might be to define a [generic function](https://docs.sqlalchemy.org/en/20/core/functions.html#sqlalchemy.sql.functions.GenericFunction), but I'm not sure exactly how we could do this to combine a `group_concat` (or [aggregate_strings](https://docs.sqlalchemy.org/en/20/core/functions.html#sqlalchemy.sql.functions.aggregate_strings)), a `distinct`, and an `order_by`, without having the same problem as above.

I am temporarily "mocking" 

https://github.com/dieterich-lab/scimodom/blob/7d4dad0f69c5c7d9988d5dcc9c51eba4ddfdc61b/server/src/scimodom/services/modification.py#L242

by removing the `.op("ORDER BY")()`. 

Until we find a viable solution, **changes to** `scimodom.services.modification._get_base_search_query` **must be reflected into** `test_modification._mock_get_base_search_query`!

### What browser were you using?

Firefox

### What version of Sci-ModoM were you using?

master
